# data preproccessing

## import modules and configure notebook

In [1]:
import pandas as pd
import numpy as np
import swifter
import seaborn as sns
import matplotlib.pyplot


pd.set_option('max.rows', None)
pd.set_option('max.columns', None)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import log_loss, accuracy_score, f1_score
from sklearn.decomposition import PCA 
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler


%matplotlib inline

/home/robert/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

### Configurations

In [2]:
data_input_path = '../data/AllData_2_All_Details_3_OutliersRem_1_SupDep_Regions.csv'
classify_bedrock_only = False
group_superficial = True

### Import data

In [3]:
my_data = pd.read_csv(data_input_path)

In [4]:
my_data.head()

,Analysis,Geology,Province,Region,Site,SubSite,Formation,Band,Nodule,Li7,Be9,B11,Mg24,Al27,Si28,P31,S33,K39,Ca42,Sc45,Ti47,V51,Cr52,Mn55,Fe56,Co59,Ni60,Cu63,Zn68,Ga69,Ge72,As75,Rb85,Sr88,Y89,Zr90,Nb93,Mo95,Cd111,In115,Sn118,Cs133,Ba137,La139,Ce140,Pr141,Nd146,Sm147,Eu153,Gd157,Tb159,Dy163,Ho165,Er166,Tm169,Yb172,Lu175,Hf178,Ta181,Pb208,Th232,U238
0,10_FH1_1_1,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_1,15.63,0.12,48.36,154.63,943.71,464944.18,50.28,538.57,455.94,712.39,0.42,15.58,0.27,3.3,0.69,8.46,0.05,0.8,1.62,10.82,0.25,1.22,0.16,0.43,12.94,0.88,1.51,0.09,0.05,0.02,0,0.05,0.01,6.54,0.84,0.95,0.23,0.87,0.16,0.04,0.16,0.02,0.11,0.03,0.06,0.01,0.02,0,0.04,0.01,0.24,0.07,0.05
1,11_FH1_1_1,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_1,11.50,0.09,44.77,NaN,1077.11,465010.94,70.91,438.20,387.82,515.24,0.44,18.47,0.29,3.45,1.01,11.59,0.11,0.36,0.53,8.93,0.34,0.85,<0.10,0.45,13.22,0.95,1.74,0.07,<0.01,<0.02,<0.00,0.04,0.02,8.04,0.92,1.01,0.23,0.98,0.18,0.04,0.18,0.02,0.13,0.03,0.06,0.01,0.04,0.01,0.05,0,0.07,0.08,0.04
2,12_FH1_1_1,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_1,20.05,0.06,44.88,42.70,620.21,465295.41,104.47,372.66,363.71,957.89,0.76,19.89,0.55,3.25,1.21,87.99,0.21,1.68,1.53,11.98,0.25,1.71,0.13,0.43,8.52,0.87,0.93,0.1,0.02,<0.02,<0.00,0.05,0.01,3.13,0.9,1.08,0.26,0.84,0.15,0.04,0.19,0.02,0.14,0.02,0.07,0.01,0.06,0,0.02,0.01,0.46,0.05,0.05
3,13_FH1_1_2,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_2,11.16,<0.73,47.06,162.42,1143.19,NaN,56367.93,1075.89,547.55,2174.3,<0.43,42.3,0.67,152.42,4.84,145.34,0.3,2.45,5.02,17.15,0.35,2.13,<0.84,0.76,13.16,0.97,2.00,0.1,0.29,<0.18,<0.01,0.78,0.04,8.74,0.93,0.95,0.21,0.75,0.13,0.04,0.25,0.02,0.09,0.03,0.05,0,0.03,<0.00,0.08,<0.00,0.64,0.05,0.03
4,14_FH1_1_2,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_2,17.71,0.32,48.26,33.52,547.22,465027.11,44.44,464.78,278.25,1551.63,0.71,11.18,0.27,2.56,1.73,25.38,0.05,0.8,0.55,9.8,0.41,1.41,<0.12,0.28,9.90,0.9,0.90,0.08,0.04,0.1,0,0.09,0.01,2.74,0.97,1.09,0.27,1,0.17,0.04,0.19,0.02,0.15,0.03,0.05,0.01,0.05,0.01,0.02,0.01,0.59,0.06,0.09

(1606,)

### make labels for classification


def make_classes_grouped(row):
    if row['Geology'] == 'Bedrock':
        if row['Site'] == 'WB' or row['Site'] == 'BX':
            return('WB_BX')
        elif row['Site'] == 'BC' or row['Site'] == 'CS':
            return('BC_CS')
        elif row['Site'] == 'SQ' or row['Site'] == 'BP':
            return('SQ_BP')
        else:
            return(row['Site'])
    elif row['Geology'] == 'Superficial':
        if row['Region'] == 'SV' or row['Region'] == 'SE':
            return('SV_SE')
        else:
            return(row['Region'])

def make_classes_raw(row):
    if row['Geology'] == 'Bedrock':
        return(row['Site'])
    elif row['Geology'] == 'Superficial':
        return(row['Region'])

my_data['class'] = 'init'   

if group_superficial:
    my_data['class'] = my_data.apply(make_classes_grouped, axis = 1)
else:
    my_data['class'] = my_data.apply(make_classes_raw, axis = 1)

In [5]:
def make_classes_subsite(row):
    return(row['SubSite'])
my_data['class'] = my_data.swifter.apply(make_classes_subsite, axis = 1)

In [38]:
my_data.tail()

,Analysis,Geology,Province,Region,Site,SubSite,Formation,Band,Nodule,Li7,Be9,B11,Mg24,Al27,Si28,P31,S33,K39,Ca42,Sc45,Ti47,V51,Cr52,Mn55,Fe56,Co59,Ni60,Cu63,Zn68,Ga69,Ge72,As75,Rb85,Sr88,Y89,Zr90,Nb93,Mo95,Cd111,In115,Sn118,Cs133,Ba137,La139,Ce140,Pr141,Nd146,Sm147,Eu153,Gd157,Tb159,Dy163,Ho165,Er166,Tm169,Yb172,Lu175,Hf178,Ta181,Pb208,Th232,U238,class
1601,44_MDG367_2,Artefacts,NaN,NaN,Madawg,NaN,NaN,NaN,MDG367,8.37,0.75,65.51,32.90,1347.97,464405.61,144.94,773.07,669.22,246.61,0.61,36.79,1.54,6.96,0.59,161.72,0.23,2.35,0.44,8.11,1.83,1.14,0.54,1.64,12.48,0.50,2.230,0.31,0.08,0.42,0.01,0.37,0.05,2.34,0.75,0.85,0.18,0.73,0.09,0.04,0.10,0.03,0.13,0.02,0.05,0.00,0.01,0.00,0.01,0.03,0.34,0.17,0.11,NaN
1602,45_MDG367_3,Artefacts,NaN,NaN,Madawg,NaN,NaN,NaN,MDG367,10.77,0.16,55.05,32.76,1339.24,464611.17,125.81,742.93,662.40,287.43,0.63,57.23,1.43,3.61,0.71,116.81,0.19,1.53,0.44,8.75,0.61,1.00,0.60,1.64,3.93,0.52,1.370,0.26,0.07,0.15,0.01,0.25,0.04,28.69,0.57,0.65,0.14,0.58,0.08,0.03,0.14,0.02,0.08,0.01,0.04,0.01,0.03,0.01,0.05,0.03,0.36,0.16,0.12,NaN
1603,46_MDG370_1,Artefacts,NaN,NaN,Madawg,NaN,NaN,NaN,MDG370,3.05,0.68,58.17,23.46,512.46,465572.56,198.53,689.45,307.63,269.73,0.57,82.86,1.85,2.37,0.63,49.28,0.17,1.27,0.54,8.96,0.32,0.80,0.61,0.67,2.62,0.80,0.970,0.24,0.10,0.10,0.03,0.18,0.02,1.61,0.78,0.64,0.15,0.63,0.16,0.05,0.15,0.02,0.07,0.03,0.04,0.01,0.04,0.00,0.05,0.01,0.26,0.12,0.20,NaN
1604,47_MDG370_2,Artefacts,NaN,NaN,Madawg,NaN,NaN,NaN,MDG370,3.06,0.99,67.16,25.17,549.53,465382.48,168.92,808.44,321.96,266.44,0.59,17.92,0.85,5.54,0.57,44.38,0.19,0.62,0.28,8.45,0.25,0.87,0.66,0.61,2.42,2.56,0.915,0.11,0.07,0.17,0.02,0.20,0.02,1.80,0.77,0.64,0.17,0.49,0.15,0.06,0.23,0.06,0.42,0.08,0.26,0.09,0.05,0.01,0.03,0.02,0.22,0.09,0.66,NaN
1605,48_MDG370_3,Artefacts,NaN,NaN,Madawg,NaN,NaN,NaN,MDG370,3.04,0.99,62.34,25.49,532.25,465456.06,188.86,802.52,330.35,232.31,0.50,28.52,0.68,5.65,0.62,46.68,0.20,1.25,0.28,7.09,0.37,0.88,0.62,0.65,2.57,0.77,1.380,0.08,0.09,0.05,0.01,0.15,0.02,2.21,0.75,0.58,0.16,0.61,0.22,0.01,0.06,0.02,0.08,0.02,0.08,0.01,0.04,0.01,0.06,0.00,0.25,0.08,0.24,NaN

### Remove '<' signs.

In [6]:
for column_name in my_data.columns.values[9:-1]:
    def fill_less_than(row):
        if '<' in str(row[column_name]):
            return(float(row[column_name].replace('<', '').replace(',','')))
        else:
            return(float(row[column_name]))
    my_data[column_name] = my_data.swifter.apply(fill_less_than, axis = 1)

Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 14604.79it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 16990.37it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18418.76it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 21288.53it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 14934.36it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17811.86it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18032.53it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19383.21it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19143.47it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19873.06it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19146.90it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19468.81it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19234.60it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 21806.30it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18565.16it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 20684.18it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19319.11it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 20216.00it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18439.48it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19722.99it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18580.21it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18543.08it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19914.30it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 16734.99it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17429.24it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18541.91it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 15459.13it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 21545.78it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19140.32it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19256.21it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 20098.86it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18700.24it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19213.04it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 20789.58it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17923.42it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17000.66it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 14986.52it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 16501.20it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18406.02it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 16258.17it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18234.23it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18131.70it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17616.90it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18529.97it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 21098.76it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19168.20it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19866.61it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 21256.35it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17744.06it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 17466.70it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 20310.66it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 18582.37it/s]
Pandas Apply: 100%|██████████| 1606/1606 [00:00<00:00, 19133.85it/s]

### Impute na values with variable median, this is more resistant to the effect of outliers

In [7]:
for column_name in my_data.columns.values[9:-1]:
    my_data[column_name] = my_data[column_name].fillna(my_data[column_name].median())

In [8]:
my_data.head()

,Analysis,Geology,Province,Region,Site,SubSite,Formation,Band,Nodule,Li7,Be9,B11,Mg24,Al27,Si28,P31,S33,K39,Ca42,Sc45,Ti47,V51,Cr52,Mn55,Fe56,Co59,Ni60,Cu63,Zn68,Ga69,Ge72,As75,Rb85,Sr88,Y89,Zr90,Nb93,Mo95,Cd111,In115,Sn118,Cs133,Ba137,La139,Ce140,Pr141,Nd146,Sm147,Eu153,Gd157,Tb159,Dy163,Ho165,Er166,Tm169,Yb172,Lu175,Hf178,Ta181,Pb208,Th232,U238,class
0,10_FH1_1_1,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_1,15.63,0.12,48.36,154.63,943.71,464944.18,50.28,538.57,455.94,712.39,0.42,15.58,0.27,3.30,0.69,8.46,0.05,0.80,1.62,10.82,0.25,1.22,0.16,0.43,12.94,0.88,1.51,0.09,0.05,0.02,0.00,0.05,0.01,6.54,0.84,0.95,0.23,0.87,0.16,0.04,0.16,0.02,0.11,0.03,0.06,0.01,0.02,0.00,0.04,0.01,0.24,0.07,0.05,FH1
1,11_FH1_1_1,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_1,11.50,0.09,44.77,22.42,1077.11,465010.94,70.91,438.20,387.82,515.24,0.44,18.47,0.29,3.45,1.01,11.59,0.11,0.36,0.53,8.93,0.34,0.85,0.10,0.45,13.22,0.95,1.74,0.07,0.01,0.02,0.00,0.04,0.02,8.04,0.92,1.01,0.23,0.98,0.18,0.04,0.18,0.02,0.13,0.03,0.06,0.01,0.04,0.01,0.05,0.00,0.07,0.08,0.04,FH1
2,12_FH1_1_1,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_1,20.05,0.06,44.88,42.70,620.21,465295.41,104.47,372.66,363.71,957.89,0.76,19.89,0.55,3.25,1.21,87.99,0.21,1.68,1.53,11.98,0.25,1.71,0.13,0.43,8.52,0.87,0.93,0.10,0.02,0.02,0.00,0.05,0.01,3.13,0.90,1.08,0.26,0.84,0.15,0.04,0.19,0.02,0.14,0.02,0.07,0.01,0.06,0.00,0.02,0.01,0.46,0.05,0.05,FH1
3,13_FH1_1_2,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_2,11.16,0.73,47.06,162.42,1143.19,465099.89,56367.93,1075.89,547.55,2174.30,0.43,42.30,0.67,152.42,4.84,145.34,0.30,2.45,5.02,17.15,0.35,2.13,0.84,0.76,13.16,0.97,2.00,0.10,0.29,0.18,0.01,0.78,0.04,8.74,0.93,0.95,0.21,0.75,0.13,0.04,0.25,0.02,0.09,0.03,0.05,0.00,0.03,0.00,0.08,0.00,0.64,0.05,0.03,FH1
4,14_FH1_1_2,Bedrock,Northern,NaN,FH,FH1,Burnham,FH1,FH1_1_2,17.71,0.32,48.26,33.52,547.22,465027.11,44.44,464.78,278.25,1551.63,0.71,11.18,0.27,2.56,1.73,25.38,0.05,0.80,0.55,9.80,0.41,1.41,0.12,0.28,9.90,0.90,0.90,0.08,0.04,0.10,0.00,0.09,0.01,2.74,0.97,1.09,0.27,1.00,0.17,0.04,0.19,0.02,0.15,0.03,0.05,0.01,0.05,0.01,0.02,0.01,0.59,0.06,0.09,FH1

### Filter for known data bedrock data for training the model

In [9]:
train_data = my_data[(my_data['Geology']== 'Bedrock') | (my_data['Geology'] == 'Superficial')]
test_data = my_data[my_data['Geology']=='Artefacts']

### label encode the class to be predicted

In [10]:
train_data_formodel = train_data.copy(deep = True)
if classify_bedrock_only == False: 
    train_data_formodel['class'], uniques = pd.factorize(train_data_formodel['class'])

rf

### order of class labels as numbers 0 through 20

In [11]:
if classify_bedrock_only == False: 
    print(uniques)

Index(['FH1', 'FH2', 'FH3', 'ER', 'WW1', 'WW2', 'WW3', 'WW4', 'TC1', 'TC2',
       'CS1', 'CS2', 'CS3', 'BC', 'KQ1', 'KQ2', 'KQ3', 'AR1', 'AR2', 'AR3',
       'SL', 'FG', 'WB', 'BX', 'PF', 'BM', 'WH1', 'WH2', 'WH3', 'WH4', 'SQ2',
       'BP', 'WN1', 'WN5', 'WN6', 'BH1', 'BH2', 'BH3', 'BH4', 'PH', 'LB', 'AB',
       'LV', 'BR', 'KY', 'BF', 'ST', 'SH', 'CF', 'BG', 'AC', 'CR', 'GH', 'PX',
       'WF'],
      dtype='object')

In [12]:
%store train_data_formodel
%store train_data
%store test_data
%store my_data
%store uniques

Stored 'train_data_formodel' (DataFrame)
Stored 'train_data' (DataFrame)
Stored 'test_data' (DataFrame)
Stored 'my_data' (DataFrame)
Stored 'uniques' (Index)

In [13]:
train_data_bedrock = train_data[train_data['Geology'] == 'Bedrock']
train_data_superficial = train_data[train_data['Geology'] == 'Superficial']

In [14]:
train_data_bedrock.columns.values[9:-1]

array(['Li7', 'Be9', 'B11', 'Mg24', 'Al27', 'Si28', 'P31', 'S33', 'K39',
       'Ca42', 'Sc45', 'Ti47', 'V51', 'Cr52', 'Mn55', 'Fe56', 'Co59',
       'Ni60', 'Cu63', 'Zn68', 'Ga69', 'Ge72', 'As75', 'Rb85', 'Sr88',
       'Y89', 'Zr90', 'Nb93', 'Mo95', 'Cd111', 'In115', 'Sn118', 'Cs133',
       'Ba137', 'La139', 'Ce140', 'Pr141', 'Nd146', 'Sm147', 'Eu153',
       'Gd157', 'Tb159', 'Dy163', 'Ho165', 'Er166', 'Tm169', 'Yb172',
       'Lu175', 'Hf178', 'Ta181', 'Pb208', 'Th232', 'U238'], dtype=object)

In [15]:
element_data_train = train_data[train_data.columns.values[9:-1]]
element_data_train_bedrock = train_data_bedrock[train_data.columns.values[9:-1]]
element_data_train_superficial = train_data_superficial[train_data.columns.values[9:-1]]
element_data_test = test_data[test_data.columns.values[9:-1]]

In [16]:
my_scaler_train = StandardScaler()
my_scaler_train_bedrock = StandardScaler()
my_scaler_train_superficial = StandardScaler()
my_scaler_test = StandardScaler()

In [17]:
element_data_train_scaled = my_scaler_train.fit_transform(element_data_train)
element_data_train_bedrock_scaled = my_scaler_train_bedrock.fit_transform(element_data_train_bedrock)
element_data_train_superficial_scaled = my_scaler_train_superficial.fit_transform(element_data_train_superficial)
element_data_test_scaled = my_scaler_test.fit_transform(element_data_test)

In [18]:
my_pca_train = PCA(n_components=element_data_train_scaled.shape[1])

my_pca_train_bedrock = PCA(n_components=element_data_train_bedrock_scaled.shape[1])
my_pca_train_superficial = PCA(n_components=element_data_train_superficial_scaled.shape[1])

my_pca_test = PCA(n_components=element_data_test_scaled.shape[1])

element_data_train_pca = my_pca_train.fit_transform(element_data_train_scaled)

element_data_train_bedrock_pca = my_pca_train_bedrock.fit_transform(element_data_train_bedrock_scaled)
element_data_train_superficial_pca = my_pca_train_superficial.fit_transform(element_data_train_superficial_scaled)

element_data_test_pca = my_pca_test.fit_transform(element_data_test_scaled)

In [19]:
no_PCs = element_data_train_scaled.shape[1]
PC_names = []
for i in range(0, no_PCs):
    number = i + 1
    column_name = 'PC' + str(number)
    PC_names.append(column_name)

In [20]:
PC_df_train = pd.DataFrame(data = element_data_train_pca, columns = PC_names)

PC_df_bedrock_train = pd.DataFrame(data = element_data_train_bedrock_pca, columns = PC_names)
PC_df_superficial_train = pd.DataFrame(data = element_data_train_superficial_pca, columns = PC_names)

PC_df_test = pd.DataFrame(data = element_data_test_pca, columns = PC_names)

In [21]:
my_tsne_train = TSNE(n_components=3, n_iter=750, verbose=3).fit_transform(element_data_train_scaled)

my_tsne_bedrock_train = TSNE(n_components=3, n_iter=750, verbose=3).fit_transform(element_data_train_bedrock_scaled)
my_tsne_superficial_train = TSNE(n_components=3, n_iter=750, verbose=3).fit_transform(element_data_train_superficial_scaled)

my_tsne_test = TSNE(n_components=3, n_iter=750, verbose=3).fit_transform(element_data_test_scaled)

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 1243 samples in 0.038s...
[t-SNE] Computed neighbors for 1243 samples in 0.301s...
[t-SNE] Computed conditional probabilities for sample 1000 / 1243
[t-SNE] Computed conditional probabilities for sample 1243 / 1243
[t-SNE] Mean sigma: 1.771276
[t-SNE] Computed conditional probabilities in 0.155s
[t-SNE] Iteration 50: error = 77.2895203, gradient norm = 0.0831428 (50 iterations in 8.268s)

KeyboardInterrupt

In [ ]:
tsne_df_train = pd.DataFrame(data = my_tsne_train, columns = ['tsne1', 'tsne2', 'tsne3'])

tsne_df_bedrock_train = pd.DataFrame(data = my_tsne_bedrock_train, columns = ['tsne1', 'tsne2', 'tsne3'])
tsne_df_superficial_train = pd.DataFrame(data = my_tsne_superficial_train, columns = ['tsne1', 'tsne2', 'tsne3'])

tsne_df_test = pd.DataFrame(data = my_tsne_test, columns = ['tsne1', 'tsne2', 'tsne3'])

In [ ]:
%store PC_df_train
%store my_pca_train

%store PC_df_bedrock_train
%store my_pca_train_bedrock

%store PC_df_superficial_train
%store my_pca_train_superficial

%store PC_df_test
%store my_pca_test

%store tsne_df_train

%store tsne_df_bedrock_train
%store tsne_df_superficial_train


%store tsne_df_test

import pandas as pd
%store -r tsne_df_train
tsne_df_train.to_csv('tsne_df_train.csv', index = False)
%store -r tsne_df_test
tsne_df_test.to_csv('tsne_df_test.csv', index=False)

%store -r PC_df_train
PC_df_train.to_csv(' PC_df_train.csv', index=False)
%store -r PC_df_test
PC_df_test.to_csv('PC_df_test.csv', index=False)